### ISSUE TITLE
Minimal python image for template API

### ISSUE THREAD

**Issue by h4c5** [France-Travail/gabarit#166]
### Problem

The current python image in [gabarit/template_api/api_project/Dockerfile](https://github.com/OSS-Pole-Emploi/gabarit/blob/main/gabarit/template_api/api_project/Dockerfile) is `python:3.8`, we should try to use a `python-slim` image by default to save ressources.

## Concerned template

  - [ ] NLP template
  - [ ] NUM template
  - [ ] VISION template
  - [x] API template
  - [ ] How templates are generated - Jinja

### Solution
```diff
# file : gabarit/template_api/api_project/Dockerfile

# base image
-FROM python:3.8 
+FROM python:3.8-slim-bookworm
```

**Comment by gsolard** [comment]
Done in PR #192
